name: Build & Deploy Lambda on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        run: |
          IMAGE_URI=786055265018.dkr.ecr.eu-west-1.amazonaws.com/lambda_volatilidad:latest
          docker build -t lambda_volatilidad ./lambda_volatilidad
          docker tag lambda_volatilidad:latest $IMAGE_URI
          docker push $IMAGE_URI

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init, Plan & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
